# Generated by Django 6.0.1 on 2026-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_lesson_description_and_more'),
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='courses.lesson'),
        ),
    ]
