# Generated by Django 6.0.1 on 2026-01-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_courses_user_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='courses',
            new_name='enrolled_courses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lessons',
            new_name='enrolled_lessons',
        ),
    ]
