# Generated by Django 6.0.1 on 2026-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_lesson_description_and_more'),
        ('users', '0005_rename_courses_user_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrolled_lessons',
            field=models.ManyToManyField(blank=True, related_name='enrolled_lessons', to='courses.lesson'),
        ),
    ]
