# Generated by Django 6.0.1 on 2026-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Стоимость курса'),
        ),
    ]
