# Generated by Django 5.2.10 on 2026-01-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('courses', '0006_course_created_at_course_last_updated_course_owner_and_more'),
    ]

    operations = [
    ]
